In [1]:
import pandas as pd
df = pd.read_csv("car_price_prediction.csv")

In [38]:
import numpy as np

In [2]:
df.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19237 non-null  int64
 1   Price             19237 non-null  int64
 2   Levy              19237 non-null  object
 3   Manufacturer      19237 non-null  object
 4   Model             19237 non-null  object
 5   Prod. year        19237 non-null  int64
 6   Category          19237 non-null  object
 7   Leather interior  19237 non-null  object
 8   Fuel type         19237 non-null  object
 9   Engine volume     19237 non-null  object
 10  Mileage           19237 non-null  object
 11  Cylinders         19237 non-null  float64
 12  Gear box type     19237 non-null  object
 13  Drive wheels      19237 non-null  object
 14  Doors             19237 non-null  object
 15  Wheel             19237 non-null  object
 16  Color             19237 non-null  object
 17  Airbags           19237 non-null  int64
dtypes: float64(1), int64(4), object(13)
memory usage: 2.6+ MB

In [4]:
df.shape

(19237, 18)

In [5]:
df['Prod. year'].unique()

array([2010, 2011, 2006, 2014, 2016, 2013, 2007, 1999, 1997, 2018, 2008,
       2012, 2017, 2001, 1995, 2009, 2000, 2019, 2015, 2004, 1998, 1990,
       2005, 2003, 1985, 1996, 2002, 1993, 1992, 1988, 1977, 1989, 1994,
       2020, 1984, 1986, 1991, 1983, 1953, 1964, 1974, 1987, 1943, 1978,
       1965, 1976, 1957, 1980, 1939, 1968, 1947, 1982, 1981, 1973],
      dtype=int64)

In [6]:
df['Price'].unique()

array([13328, 16621,  8467, ..., 56814, 63886, 22075], dtype=int64)

In [7]:
# pretty clean data, no null values

In [8]:
df['Manufacturer'].unique()

array(['LEXUS', 'CHEVROLET', 'HONDA', 'FORD', 'HYUNDAI', 'TOYOTA',
       'MERCEDES-BENZ', 'OPEL', 'PORSCHE', 'BMW', 'JEEP', 'VOLKSWAGEN',
       'AUDI', 'RENAULT', 'NISSAN', 'SUBARU', 'DAEWOO', 'KIA',
       'MITSUBISHI', 'SSANGYONG', 'MAZDA', 'GMC', 'FIAT', 'INFINITI',
       'ALFA ROMEO', 'SUZUKI', 'ACURA', 'LINCOLN', 'VAZ', 'GAZ',
       'CITROEN', 'LAND ROVER', 'MINI', 'DODGE', 'CHRYSLER', 'JAGUAR',
       'ISUZU', 'SKODA', 'DAIHATSU', 'BUICK', 'TESLA', 'CADILLAC',
       'PEUGEOT', 'BENTLEY', 'VOLVO', 'სხვა', 'HAVAL', 'HUMMER', 'SCION',
       'UAZ', 'MERCURY', 'ZAZ', 'ROVER', 'SEAT', 'LANCIA', 'MOSKVICH',
       'MASERATI', 'FERRARI', 'SAAB', 'LAMBORGHINI', 'ROLLS-ROYCE',
       'PONTIAC', 'SATURN', 'ASTON MARTIN', 'GREATWALL'], dtype=object)

In [9]:
df["Model"].unique()

array(['RX 450', 'Equinox', 'FIT', ..., 'E 230 124', 'RX 450 F SPORT',
       'Prius C aqua'], dtype=object)

In [10]:
df.describe()

                 ID         Price    Prod. year     Cylinders       Airbags
count  1.923700e+04  1.923700e+04  19237.000000  19237.000000  19237.000000
mean   4.557654e+07  1.855593e+04   2010.912824      4.582991      6.582627
std    9.365914e+05  1.905813e+05      5.668673      1.199933      4.320168
min    2.074688e+07  1.000000e+00   1939.000000      1.000000      0.000000
25%    4.569837e+07  5.331000e+03   2009.000000      4.000000      4.000000
50%    4.577231e+07  1.317200e+04   2012.000000      4.000000      6.000000
75%    4.580204e+07  2.207500e+04   2015.000000      4.000000     12.000000
max    4.581665e+07  2.630750e+07   2020.000000     16.000000     16.000000

In [11]:
df['Mileage']=df['Mileage'].str.replace('km', '')

In [12]:
df['Mileage']=df['Mileage'].astype(str).astype(int)

In [13]:
#checked for inconsistencies data is clean

In [14]:
df[df['Price']>2.5e6]

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
16983,45812886,26307500,-,OPEL,Combo,1999,Goods wagon,No,Diesel,1.7,99999,4.0,Manual,Front,02-Mar,Left wheel,Blue,0

In [15]:
df = df[df['Price']<2.5e6].reset_index(drop=True)

In [16]:
df[df['Price']<100]

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
27,45804684,30,-,TOYOTA,Prius,2008,Sedan,No,Hybrid,1.5,169000,4.0,Automatic,Front,04-May,Left wheel,White,8
117,45624923,94,-,HONDA,FIT,2003,Hatchback,No,Petrol,1.5,178000,4.0,Variator,Front,04-May,Right-hand drive,Silver,4
214,45721264,30,-,HONDA,FIT,2002,Hatchback,No,Petrol,1.5,0,4.0,Automatic,Front,04-May,Right-hand drive,Silver,4
221,45612423,3,-,HYUNDAI,Elantra,2011,Sedan,Yes,Petrol,1.8,80000,4.0,Tiptronic,Front,04-May,Left wheel,Grey,6
253,32116317,50,-,TOYOTA,Aqua,2013,Sedan,No,Hybrid,1.5,130000,4.0,Automatic,Rear,04-May,Right-hand drive,Sky blue,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19102,45748748,30,-,NISSAN,Tiida,2006,Hatchback,No,Petrol,1.5,0,4.0,Automatic,Front,04-May,Right-hand drive,Black,4
19147,45303823,30,-,HONDA,FIT,2005,Hatchback,No,Petrol,1.3,169000,4.0,Automatic,Front,04-May,Right-hand drive,White,4
19163,45040734,60,-,TOYOTA,Prius,2013,Sedan,No,Hybrid,1.8,150000,4.0,Automatic,Front,04-May,Left wheel,White,8
19217,45748699,30,-,NISSAN,Note,2006,Hatchback,No,Petrol,1.3,0,4.0,Automatic,Front,04-May,Right-hand drive,Green,9
19228,39977395,50,-,TOYOTA,Prius,2008,Hatchback,No,Hybrid,1.5,150000,4.0,Automatic,Front,04-May,Left wheel,Silver,6

In [17]:
df = df[df['Price']>500].reset_index(drop=True)

In [18]:
df.describe()

,ID,Price,Prod. year,Mileage,Cylinders,Airbags
count,1.757100e+04,17571.00000,17571.000000,1.757100e+04,17571.000000,17571.000000
mean,4.560530e+07,18793.70235,2010.849126,1.475782e+06,4.556371,6.480735
std,7.526060e+05,19971.36149,5.678049,4.725168e+07,1.183959,4.201473
min,2.436776e+07,549.00000,1943.000000,0.000000e+00,1.000000,0.000000
25%,4.572036e+07,7674.00000,2009.000000,7.002350e+04,4.000000,4.000000
50%,4.577503e+07,14426.00000,2012.000000,1.248920e+05,4.000000,4.000000
75%,4.580223e+07,23521.00000,2015.000000,1.850000e+05,4.000000,12.000000
max,4.581665e+07,872946.00000,2020.000000,2.147484e+09,16.000000,16.000000

In [19]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17566,45772306,5802,1055,MERCEDES-BENZ,E 350,2013,Sedan,Yes,Diesel,3.5,107800,6.0,Automatic,Rear,04-May,Left wheel,Grey,12
17567,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
17568,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
17569,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365,4.0,Automatic,Front,04-May,Left wheel,Grey,4
17570,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258,4.0,Automatic,Front,04-May,Left wheel,Black,4

In [20]:
##Model

In [21]:
X=df.drop(['Price','Engine volume','Cylinders','Doors','Wheel','Gear box type', 'Leather interior','ID','Levy','Color', 'Fuel type', 'Fuel type', 'Drive wheels', 'Airbags' ], axis=1)
y=df['Price']

In [22]:
X

        Manufacturer    Model  Prod. year   Category  Mileage
0              LEXUS   RX 450        2010       Jeep   186005
1          CHEVROLET  Equinox        2011       Jeep   192000
2              HONDA      FIT        2006  Hatchback   200000
3               FORD   Escape        2011       Jeep   168966
4              HONDA      FIT        2014  Hatchback    91901
...              ...      ...         ...        ...      ...
17566  MERCEDES-BENZ    E 350        2013      Sedan   107800
17567  MERCEDES-BENZ  CLK 200        1999      Coupe   300000
17568        HYUNDAI   Sonata        2011      Sedan   161600
17569        HYUNDAI   Tucson        2010       Jeep   116365
17570      CHEVROLET  Captiva        2007       Jeep    51258

[17571 rows x 5 columns]

In [23]:
y

0        13328
1        16621
2         8467
3         3607
4        11726
         ...
17566     5802
17567     8467
17568    15681
17569    26108
17570     5331
Name: Price, Length: 17571, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .2)

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [26]:
ohe = OneHotEncoder()
ohe.fit(X[['Model', 'Manufacturer','Category']])

OneHotEncoder()

In [27]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_), ['Model', 'Manufacturer','Category']), remainder='passthrough')

In [28]:
lr = LinearRegression()

In [29]:
pipe = make_pipeline(column_trans, lr)

In [30]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['09-Mar', '100', '100 NX', ..., 'macan S', 'tC', 'xD'],
      dtype=object),
                                                                            array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'CITROEN', 'DAEWOO',
       'DAIHATSU', 'DODGE', 'F...
       'ROVER', 'SAAB', 'SATURN', 'SCION', 'SEAT', 'SKODA', 'SSANGYONG',
       'SUBARU', 'SUZUKI', 'TESLA', 'TOYOTA', 'UAZ', 'VAZ', 'VOLKSWAGEN',
       'VOLVO', 'ZAZ', 'სხვა'], dtype=object),
                                                                            array(['Cabriolet', 'Coupe', 'Goods wagon', 'Hatchback', 'Jeep',
       'Limousine', 'Microbus', 'Minivan', 'Pickup', 'Sedan', 'Universal'],
      dtype=object)]),
                                                  ['Model', 'Manufacturer',
                                                   'Category'])])),
                ('linearregression', LinearRegression())])

In [31]:
lr = LinearRegression()

In [32]:
pipe=make_pipeline(column_trans, lr)

In [33]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['09-Mar', '100', '100 NX', ..., 'macan S', 'tC', 'xD'],
      dtype=object),
                                                                            array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'CITROEN', 'DAEWOO',
       'DAIHATSU', 'DODGE', 'F...
       'ROVER', 'SAAB', 'SATURN', 'SCION', 'SEAT', 'SKODA', 'SSANGYONG',
       'SUBARU', 'SUZUKI', 'TESLA', 'TOYOTA', 'UAZ', 'VAZ', 'VOLKSWAGEN',
       'VOLVO', 'ZAZ', 'სხვა'], dtype=object),
                                                                            array(['Cabriolet', 'Coupe', 'Goods wagon', 'Hatchback', 'Jeep',
       'Limousine', 'Microbus', 'Minivan', 'Pickup', 'Sedan', 'Universal'],
      dtype=object)]),
                                                  ['Model', 'Manufacturer',
                                                   'Category'])])),
                ('linearregression', LinearRegression())])

In [34]:
y_pred = pipe.predict(X_test)

In [35]:
y_pred

array([18707.00537232, 18706.31088154, 18707.78651218, ...,
       18707.09727112, 18707.65693486, 18707.24086301])

In [36]:
r2_score(y_test, y_pred)

-0.00011705977727394234

In [43]:
score=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2, random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans, lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    score.append(r2_score(y_test,y_pred))

In [44]:
np.argmax(score)

940

In [45]:
score[np.argmax(score)]

0.0007369269576149584

In [48]:
import pickle

In [49]:
pickle.dump(pipe, open("LinearRegressionModel.pkl","wb"))

In [59]:
pipe.predict(pd.DataFrame([["TOYOTA","RAV 4", "Jeep", 2015, 50000]], columns=['Manufacturer', 'Model','Category', 'Prod. year', 'Mileage']))

array([18721.40091031])